### ISSUE TITLE
Error building/installing

### ISSUE THREAD

**Issue by andrewharvey** [osmcode/node-osmium#64]
I can't seem to install using `npm install osmium` nor can I build from source using `make`. I'm running Debian unstable.

I get `../src/apply.cpp:10:40: fatal error: osmium/io/input_iterator.hpp: No such file or directory`

I've attached the logs.

[make.txt](https://github.com/osmcode/node-osmium/files/35093/make.txt)
[npm-install-osmium.txt](https://github.com/osmcode/node-osmium/files/35094/npm-install-osmium.txt)

**Comment by springmeyer** [comment]
Per the note at https://github.com/osmcode/node-osmium#depends, `node-osmium` only works with Node v0.10.x. You are using 4.x.

**Comment by andrewharvey** [comment]
That makes sense, thanks. I'll try again using v0.10.x.
